const ar = {
  // Header title Global
  home: 'الرئيسية',
  dashboard: 'لوحة التحكم',
  profile: 'الملف الشخصي',
  employees: 'الموظفين',
  addEmployeeLink: 'اضافة موظف',
  about: 'عن الشركة',
  contact: 'اتصل بنا',
  uploadFile: 'رفع ملف',
  // Header title Global End
  // Authentication
  logout: 'تسجيل خروج',
  login: 'تسجيل دخول',
  // Authentication End
  // variables Global
  okText: 'تأكيد',
  cancelText: 'الغاء',
  loginFirst: 'الرجاء تسجيل الدخول',
  canceled: 'تم الغاء العملية',
  delete: 'حذف',
  edit: 'تعديل',
  name: 'الاسم',
  save: 'حفظ',
  search: 'بحث',
  add: 'اضافة',
  male: 'ذكر',
  female: 'انثى',
  notFound: ' الصفحة غير موجودة',
  notDesc1: 'لم نتمكن من العثور على ما كنت تبحث عنه.',
  notDesc2:
    ' يرجى الاتصال بمالك الموقع الذي ربطك بالموقع الأصلي URL وأخبرهم أن الرابط الخاص بهم معطل.',
  notBtn: 'العودة الى الرئيسية',
  am: 'صباحا',
  pm: 'مساء',
  // variables Global End
  date: 'التاريخ',
  time: 'الوقت',
  duty: 'فعال',
  offduty: 'غير فعال',
  title: 'الراتب',
  phone: 'الهاتف',
  id: 'رقم الموظف',
  // calculationSystem
  calculationTitle: 'نظام الحساب',
  calculationTitle1: 'لما الموظف يتاخر اقل من',
  calculationTitle2: 'ربع ساعه',
  calculationTitle3: 'عن موعد حضوره اخصم',
  calculationTitle4: 'من مرتبه اليومي % ',
  // calculationSystem End
  // employee info
  deleteEmployee: 'حذف الموظف',
  deleteMes:"هل تريد حذف هذا الموظف؟",
  deletedesc:"هل انت متاكد من حذف هذا الموظف؟",
  successDelete:"تم حذف الموظف بنجاح",
  employeePage: 'صفحة الموظف',
  serialNumber: 'رقم التسلسل:',
  job: 'الوظيفة:',
  gender: 'النوع:',
  maritalStatus: 'الحالة الاجتماعية:',
  maritalStatus1: 'متزوج',
  maritalStatus2: 'اعزب',
  age: 'العمر:',
  lastCaptured: 'تاريخ اخر قبض:',
  dateBirth: 'تاريخ الميلاد:',
  status: 'الحالة:',
  status1: 'قيد العمل',
  status2: 'متدرب',
  status3: 'مفصول',
  dateJoin: 'تاريخ الانضمام الي الشركة:',
  dataEit: 'تاريخ الخروج من الشركة:',
  study: 'الدراسة:',
  study1: 'طالب',
  study2: 'خريج',
  study3: 'دوام كامل',
  dataLast: 'تاريخ اخر ضبط:',
  salary: 'الراتب:',
  searchName:"البحث بـ الاسم",
  // employee info End
  // table salary
  salaryTable: 'مواعيد حضوره وانصرافه لاخر شهر قبضه',
  history: 'التاريخ',
  entrance: 'دخول',
  exit: 'خروج',
  datesAttendance: 'مواعيد حضوره',
  datesExit: 'مواعيد الانصراف',
  absences: 'غيابات',
  datesArrest: ' تواريخ القبض',
  basicSalary: 'الراتب الاساسي',
  additional: 'الاضافي',
  delays: 'التاخيرات',
  deductions: 'الخصومات',
  bonuses: 'المكافات',
  target: 'التارجت',
  balanceDeb: 'رصيد الدين اللي عليه',
  balanceCred: 'الديون المقتطعه',
  balance: 'المرتب الصافي',
  comments: 'التعليقات',
  departmentFinance: 'قسم المالية',
  // table salary End
  // Login
  loginTitle: 'تسجيل دخول',
  email: 'البريد الالكتروني',
  password: 'كلمة المرور',
  forgetPassword: 'نسيت كلمة المرور؟',
  userName: 'اسم المستخدم',
  requiredName: 'يرجى أدخال اسم المستخدم',
  requiredEmail: 'يرجى أدخال البريد الالكتروني',
  requiredPassword: 'يرجى أدخال كلمة المرور',
  noAccount: 'ليس لديك حساب؟',
  register: 'تسجيل حساب',
  // Login End
  // Register
  registerTitle: 'تسجيل حساب',
  account: 'لديك حساب؟',
  // Register End
  // Add Employee
  addEmployee: 'اضافة موظف',
  requiredNameMin: 'يجب أن يتكون الاسم من 10 أحرف على الأقل',
  requireJob: 'يرجى أدخال الوظيفة',
  workingStatus: 'الحالة العملية',
  requireGender: 'يرجى أدخال النوع',
  requireWorkingStatus: 'يرجى أدخال الحالة العملية',
  trainee: 'متدرب',
  employed: 'موظف',
  graduate: 'خريج',
  fullTime: 'دوام كامل',
  birthDate: 'تاريخ الميلاد',
  requiredBirthDate: 'يرجى أدخال تاريخ الميلاد',
  joinedDate: 'تاريخ الانضمام',
  requiredJoinedDate: 'يرجى أدخال تاريخ الانضمام',
  requiredBasicSalary: 'يرجى أدخال الراتب الاساسي',
  education: 'التعليم',
  graduated: 'متخرج',
  others: 'اخرى',
  // Add Employee End
};

export default ar