const en = {
  // Header title Global
  home: 'Home',
  dashboard: 'Dashboard',
  profile: 'Profile',
  employees: 'Employees',
  addEmployeeLink: 'Add Employee',
  about: 'About',
  contact: 'Contact',
  uploadFile: 'Upload File',
  // Header title Global End
  // Authentication
  logout: 'Log out',
  login: 'Login',
  // Authentication  End
  // variables Global
  okText: 'OK',
  cancelText: 'Cancel',
  loginFirst: 'Please login first',
  canceled: 'Canceled',
  delete: 'Delete',
  edit: 'Edit',
  save: 'Save',
  search: 'Search',
  add: 'Add',
  name: 'Name',
  male: 'Male',
  female: 'Female',
  notFound: 'Not Found',
  notDesc1: 'Could not find what you are looking for.',
  notDesc2:
    ' Please contact the owner of the website who linked your URL and inform them that the link is broken.',
  notBtn: 'Back to home',
  am: 'AM',
  pm: 'PM',
  // variables Global End
  date: 'Date',
  time: 'Time',
  duty: 'On duty',
  offduty: 'Off duty',
  title: 'Salary',
  phone: 'Phone',
  id: 'employee number',
  // calculationSystem
  calculationTitle: 'Calculation System',
  calculationTitle1: 'For employees who work less than',
  calculationTitle2: 'an hour',
  calculationTitle3: 'for an absence, deduct',
  calculationTitle4: 'from their salary %',
  // calculationSystem End
  // employee info
  deleteEmployee: 'Delete Employee',
  deleteMes:"Are you sure you want to delete this employee?",
  deletedesc:"Are you sure you want to delete this employee?",
  successDelete:"Employee deleted successfully",
  employeePage: 'Employee Page',
  serialNumber: 'Serial Number:',
  job: 'Job:',
  gender: 'Gender:',
  maritalStatus: 'Marital Status:',
  maritalStatus1: 'Married',
  maritalStatus2: 'Single',
  age: 'Age:',
  lastCaptured: 'Last Captured Date:',
  dateBirth: 'Date of Birth:',
  status: 'Status:',
  status1: 'On duty',
  status2: 'Trainee',
  status3: 'Separated',
  dateJoin: 'Date of joining the company:',
  dataEit: 'Date of exit from the company:',
  study: 'Study:',
  study1: 'Student',
  study2: 'Graduate',
  study3: 'Full-time',
  dataLast: 'Date of the last time his salary was raised:',
  salary: 'Salary:',
  searchName:"Search by name",
  // employee info End
  // table salary
  salaryTable: 'Attendance and exit of the last month of his salary',
  history: 'History',
  entrance: 'Entrance',
  exit: 'Exit',
  datesAttendance: 'Dates of attendance',
  departureDates: 'Departure Dates',
  datesExit: 'Dates of exit',
  absences: 'Absences',

  datesArrest: 'Dates of arrest',
  basicSalary: 'Basic salary',
  additional: 'Additional',
  delays: 'Delays',
  deductions: 'Deductions',
  bonuses: 'Bonuses',
  target: 'Target',
  balanceDeb: ' balance of the debt that he owes',
  balanceCred: 'Balance of the credit',
  netSalary: 'Net salary',
  comments: 'Comments',
  departmentFinance: 'Department of Finance',
  // table salary End
  // Login
  loginTitle: 'Login',
  email: 'Email',
  password: 'Password',
  forgetPassword: 'Forget your password?',
  userName: 'Name',
  requiredName: 'Please enter your name',
  requiredEmail: 'Please enter your email',
  requiredPassword: 'Please enter your password',
  noAccount: "Don't have an account?",
  register: 'Register',
  // Login End
  // Register
  registerTitle: 'Register',
  account: ' Already have an account?',
  // Register End
  // Add Employee
  addEmployee: 'Add Employee',
  requiredNameMin: 'Name must be at least 10 characters',
  requireJob: 'Please enter your job',
  requireGender: 'Please enter your gender',
  workingStatus: 'Working Status',
  requireWorkingStatus: 'Please enter your working status',
  trainee: 'Trainee',
  employee: 'Employee',
  graduate: 'Graduate',
  dismissed: 'Dismissed',
  fullTime: 'Full-time',
  birthDate: 'Date of Birth',
  requiredBirthDate: 'Please enter your date of birth',
  joinedDate: 'Date of joining the company',
  requiredJoinedDate: 'Please enter your date of joining the company',
  requiredBasicSalary: 'Please enter your basic salary',
  education: 'Education',
  graduated: 'Graduated',
  others: 'Others',
  // Add Employee End
};

export default en